variables:
  package_name: "sdl2"
  package_version: "2.0.8"
  package_user: "stever"
  package_channel: "testing"
  package_repo: "conan"

stages:
  - build

android:
  image: registry.gitlab.com/ssrobins/docker-android-build
  stage: build
  script:
    # Environment
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    # Build
    - export ANDROID_HOME=/root
    - conan create . ${package_user}/${package_channel} -s arch=armv7 -s compiler=clang -s compiler.version=7.0 -s compiler.libcxx=libstdc++11
    - conan remote add ${package_repo} https://api.bintray.com/conan/${package_user}/${package_repo}
    - conan user -p ${CONAN_API_KEY} -r ${package_repo} ${package_user}
    - conan upload ${package_name}/${package_version}@${package_user}/${package_channel} -r ${package_repo} --all

linux:
  image: registry.gitlab.com/ssrobins/docker-linux-build
  stage: build
  script:
    # Environment
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    # Build
    - conan create . ${package_user}/${package_channel}
    - conan remote add ${package_repo} https://api.bintray.com/conan/${package_user}/${package_repo}
    - conan user -p ${CONAN_API_KEY} -r ${package_repo} ${package_user}
    - conan upload ${package_name}/${package_version}@${package_user}/${package_channel} -r ${package_repo} --all

mac:
  stage: build
  script:
    - conan create . ${package_user}/${package_channel}
    - conan upload ${package_name}/${package_version}@${package_user}/${package_channel} -r ${package_repo} --all
  tags:
    - mac

windows:
  stage: build
  script:
    - conan create . %package_user%/%package_channel% -s arch=x86 -s compiler.runtime=MT
    - conan upload %package_name%/%package_version%@%package_user%/%package_channel% -r %package_repo% --all
  tags:
    - windows
