variables:
  package_name: "zlib"
  package_version: "1.2.11"
  package_user: "stever"
  package_channel: "testing"
  cmake_version_major: "3"
  cmake_version_minor: "13"
  cmake_version_patch: "0-rc1"
  cmake_installer: "cmake-${cmake_version_major}.${cmake_version_minor}.${cmake_version_patch}-Linux-x86_64.sh"

stages:
  - build

linux:
  image: gcc:8.2.0
  stage: build
  script:
    # Environment
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - gcc --version
    # Python
    - apt update && apt -y install python3-pip
    # Conan
    - pip3 install conan
    # CMake
    - wget --no-verbose https://cmake.org/files/v${cmake_version_major}.${cmake_version_minor}/${cmake_installer}
    - sh ./${cmake_installer} --prefix=/usr --skip-license
    # Build
    - conan create . ${package_user}/${package_channel}

mac:
  stage: build
  script:
    - conan create . ${package_user}/${package_channel}
    - conan upload ${package_name}/${package_version}@${package_user}/${package_channel} -r conan --all
  tags:
    - mac

windows:
  stage: build
  script:
    - conan create . %package_user%/%package_channel% -s arch=x86 -s compiler.runtime=MT
    - conan upload %package_name%/%package_version%@%package_user%/%package_channel% -r conan --all
  tags:
    - windows