variables:
  CONAN_USERNAME: "stever"
  CONAN_USER_HOME: "$CI_PROJECT_DIR"

stages:
  - build

before_script:
  - cmake --version
  - conan --version
  - conan remote add conan https://api.bintray.com/conan/stever/conan

.android:
  image: registry.gitlab.com/ssrobins/docker-android-build:jdk8u212b04-ndk19c
  stage: build
  script:
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - java -version
    - conan user -p $CONAN_API_KEY -r conan stever
    - ./build_$android_arch.sh
    - conan upload "*" --all -r conan -c
  except:
    variables:
      - $desktop_only == "true"

android-v7a:
  variables:
    android_arch: "android-v7a"
  extends: .android

android-v8a:
  variables:
    android_arch: "android-v8a"
  extends: .android

ios:
  stage: build
  script:
    - conan user -p $CONAN_API_KEY -r conan stever
    - ./build_ios.sh
    - conan upload "*" --all -r conan -c
  tags:
    - mac
  except:
    variables:
      - $desktop_only == "true"

linux:
  image: registry.gitlab.com/ssrobins/docker-linux-build:gcc9.1.0
  stage: build
  script:
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - gcc --version
    - conan user -p $CONAN_API_KEY -r conan stever
    - ./build_linux.sh
    - conan upload "*" --all -r conan -c

mac:
  stage: build
  script:
    - conan user -p $CONAN_API_KEY -r conan stever
    - ./build_mac.sh
    - conan upload "*" --all -r conan -c
  tags:
    - mac

windows:
  stage: build
  script:
    - conan user -p %CONAN_API_KEY% -r conan stever
    - call build_windows.bat
    - conan upload "*" --all -r conan -c
  tags:
    - windows
