stages:
  - build

linux:
  image: gcc:8.2.0
  stage: build
  script:
    # Environment
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - gcc --version
    # Python
    - apt update && apt -y install python3-pip
    # Conan
    - pip3 install conan
    # Build
    - conan create . stever/testing

windows:
  stage: build
  script:
    - conan create . stever/testing
  tags:
    - windows