variables:
  CONAN_USER_HOME: "$CI_PROJECT_DIR"
  CONAN_REVISIONS_ENABLED: "1"

stages:
  - build

before_script:
  - cmake --version
  - conan --version
  - conan remote add conan https://api.bintray.com/conan/stever/conan
  - conan user --password $CONAN_API_KEY --remote conan stever

.android:
  image: registry.gitlab.com/ssrobins/docker-android-build:jdk8u212b04-ndk20
  stage: build
  script:
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - java -version
    - ./build_$android_arch.sh
    - conan upload $(conan inspect --raw name .) --all --remote conan --confirm
  except:
    variables:
      - $desktop_only == "true"

android-v7a:
  variables:
    android_arch: "android-v7a"
  extends: .android

android-v8a:
  variables:
    android_arch: "android-v8a"
  extends: .android

ios:
  stage: build
  script:
    - ./build_ios.sh
    - conan upload $(conan inspect --raw name .) --all --remote conan --confirm
  tags:
    - mac
  except:
    variables:
      - $desktop_only == "true"

linux:
  image: registry.gitlab.com/ssrobins/docker-linux-build:gcc9.1.0
  stage: build
  script:
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - gcc --version
    - ./build_linux.sh
    - conan upload $(conan inspect --raw name .) --all --remote conan --confirm

mac:
  stage: build
  script:
    - ./build_mac.sh
    - conan upload $(conan inspect --raw name .) --all --remote conan --confirm
  tags:
    - mac

windows:
  stage: build
  script:
    - .\build_windows.bat
    - conan upload $(conan inspect --raw name .) --all --remote conan --confirm
  tags:
    - windows
